export ZSH=/home/docker/.oh-my-zsh

ZSH_THEME="ys"

plugins=(git golang zsh-syntax-highlighting zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

bindkey -v

export LANG=en_US.UTF-8
export EDITOR="vim"
export SHELL="/bin/zsh"

alias gomt="go mod tidy"
alias gomv="go mod vendor"

gnb () {
	name="$@"
	name=${name:gs/ /_}
	name=${name:gs/:/}
	echo "Create branch $name [y/N]?"
	read -r -s -k 1 COMMAND
	if [ "$COMMAND" = "y" ]
	then
		git checkout master
		git pull -v
		git checkout -b $name
	else
		echo "abort."
	fi
}

[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
[[ -f ~/.nvm/nvm.sh ]] && source ~/.nvm/nvm.sh
